package exception

class MyException: java.lang.Exception {
 internal constructor()

 internal constructor(cause: kotlin.Throwable?): super(cause)
}
